# Generated by Django 4.0.6 on 2022-12-04 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
